services:
  lorekeeper: 
    build: .
    env_file:
      - path: ".env"
    volumes: 
      - ./database:/lorekeeper/database
      - ./discord.log:/lorekeeper/discord.log

volumes:
  database: {}
  discord.log: {}